award_aliases = {
    'best motion picture - drama': [
        'best motion picture - drama',
        'best picture drama',
        'best motion picture drama',
        'best drama',
    ],
    'best performace by an actress in a motion picture - drama': [
        'best performace by an actress in a motion picture - drama',
        'best actress drama',
        'best actress motion picture',
        'best actress motion picture drama',
        'best actress motion drama',
    ],
    'best performance by an actor in a motion picture - drama': [
        'best performance by an actor in a motion picture - drama',
        'best actor drama',
        'best actor motion picture',
        'best actor motion picture drama',
        'best actor motion drama',
    ],
    'best motion picture - comedy or musical': [
        'best motion picture - comedy or musical',
        'best motion picture comedy or musical',
        'best motion picture comedy/musical',
        'best motion picture - comedy/musical',
        'best picture comedy or musical',
        'best picture comedy/musical',
        'best comedy or musical',
        'best comedy/musiscal'
    ],
    'best performance by an actress in a motion picture - comedy or musical': [
        'best performance by an actress in a motion picture - comedy or musical',
        'best actress motion picture comedy or musical',
        'best actress motion picture comedy/musical',
        'best actress comedy or musical',
        'best actress comedy/musical',
        'best actress in a comedy/musical',
        'best actress in a comedy or musical',
    ],
    'best performance by an actor in a motion picture - comedy or musical': [
        'best performance by an actor in a motion picture - comedy or musical',
        'best actor motion picture comedy or musical',
        'best actor motion picture comedy/musical',
        'best actor comedy or musical',
        'best actor comedy/musical',
        'best actor in a comedy/musical',
        'best actor in a comedy or musical',
    ],
    'best animated feature film': [
        'best animated feature film',
        'best animated film',
        'best animated',
    ],
    'best foreign language film': [
        'best foreign language film',
        'best foreign film',
    ],
    'best performance by an actress in a supporting role in a motion picture': [
        'best performance by an actress in a supporting role in a motion picture',
        'best actress in a supporting role in a motion picture',
        'best actress in a supporting role motion picture',
        'best supporting actress in a motion picture',
        'best supporting actress motion picture',        
    ],
    'best performance by an actor in a supporting role in a motion picture': [
        'best performance by an actor in a supporting role in a motion picture',
        'best actor in a supporting role in a motion picture',
        'best actor in a supporting role motion picture',
        'best supporting actor in a motion picture',
        'best supporting actor motion picture',
    ],
    'best director - motion picture': [
        'best director - motion picture',
        'best director motion picture',
        'best director',
    ],
    'best screenplay - motion picture': [
        'best screenplay - motion picture',
        'best screenplay motion picture',
        'best screenplay',
    ],
    'best original score - motion picture': [
        'best original score - motion picture',
        'best original score motion picture',
        'best score motion picture',
        'best score',
        'best original score',
    ],
    'best original song - motion picture': [
        'best original song - motion picture',
        'best original song',
        'best song',
        'best song - motion picture',
        'best song motion picture',
        'best original song motion picture',
    ],
    'best television series - drama': [
        'best television series - drama',
        'best television series drama',
        'best television drama',
        'best tv series - drama',
        'best tv series drama',
        'best tv drama',
    ],
    'best performance by an actress in a television series - drama': [
        'best performance by an actress in a television series - drama',
        'best actress in a television series drama',
        'best actress in a television drama',
        'best actress television series drama',
        'best actress television drama',
        'best performance by an actress in a tv series - drama',
        'best actress in a tv series drama',
        'best actress in a tv drama',
        'best actress tv series drama',
        'best actress tv drama',

    ],
    'best performance by an actor in a television series - drama': [
        'best performance by an actor in a television series - drama',
        'best actor in a television series drama',
        'best actor in a television drama',
        'best actor television series drama',
        'best actor television drama',
        'best performance by an actor in a tv series - drama',
        'best actor in a tv series drama',
        'best actor in a tv drama',
        'best actor tv series drama',
        'best actor tv drama',
    ],
    'best television series - comedy or musical': [
        'best television series - comedy or musical',
        'best television series comedy or musical',
        'best television comedy or musical',
        'best tv series - comedy or musical',
        'best tv series comedy or musical',
        'best tv comedy or musical'
        'best television series - comedy/musical',
        'best television series comedy/musical',
        'best television comedy/musical',
        'best tv series - comedy/musical',
        'best tv series comedy/musical',
        'best tv comedy/musical'
    ],
    'best performance by an actress in a television series - comedy or musical': [
        'best performance by an actress in a television series - comedy or musical',
        'best actress in a television series comedy or musical',
        'best actress in a television comedy or musical',
        'best actress television series comedy or musical',
        'best actress television comedy or musical',
        'best performance by an actress in a tv series - comedy or musical',
        'best actress in a tv series comedy or musical',
        'best actress in a tv comedy or musical',
        'best actress tv series comedy or musical',
        'best actress tv comedy or musical',
        'best performance by an actress in a television series - comedy/musical',
        'best actress in a television series comedy/musical',
        'best actress in a television comedy/musical',
        'best actress television series comedy/musical',
        'best actress television comedy/musical',
        'best performance by an actress in a tv series - comedy/musical',
        'best actress in a tv series comedy/musical',
        'best actress in a tv comedy/musical',
        'best actress tv series comedy/musical',
        'best actress tv comedy/musical',
    ],
    'best performance by an actor in a television series - comedy or musical': [
        'best performance by an actor in a television series - comedy or musical',
        'best actor in a television series comedy or musical',
        'best actor in a television comedy or musical',
        'best actor television series comedy or musical',
        'best actor television comedy or musical',
        'best performance by an actor in a tv series - comedy or musical',
        'best actor in a tv series comedy or musical',
        'best actor in a tv comedy or musical',
        'best actor tv series comedy or musical',
        'best actor tv comedy or musical',
        'best performance by an actor in a television series - comedy/musical',
        'best actor in a television series comedy/musical',
        'best actor in a television comedy/musical',
        'best actor television series comedy/musical',
        'best actor television comedy/musical',
        'best performance by an actor in a tv series - comedy/musical',
        'best actor in a tv series comedy/musical',
        'best actor in a tv comedy/musical',
        'best actor tv series comedy/musical',
        'best actor tv comedy/musical',
    ],
    'best mini-series or motion picture made for television': [
        'best mini-series or motion picture made for television',
        'best television miniseries or motion picture',
        'best television picture',
        'best picture television',
        'best mini-series or motion picture made for television',
        'best television miniseries or motion picture',
        'best television picture',
        'best picture television',
        'best mini-series or motion picture made for tv',
        'best tv miniseries or motion picture',
        'best tv picture',
        'best picture tv',
        'best mini-series or motion picture made for tv',
        'best tv miniseries or motion picture',
        'best tv picture',
        'best picture tv',
    ],
    'best performance by an actress in a mini-series or motion picture made for television': [
        'best performance by an actress in a mini-series or motion picture made for television',
        'best actress in a mini-series or motion picture made for television',
        'best actress in a television miniseries or motion picture',
        'best actress television miniseries',
        'best performance by an actress in a mini-series or motion picture made for tv',
        'best actress in a mini-series or motion picture made for tv',
        'best actress in a tv miniseries or motion picture',
        'best actress tv miniseries',
    ],
    'best performance by an actor in a mini-series or motion picture made for television': [
        'best performance by an actor in a mini-series or motion picture made for television',
        'best actor in a mini-series or motion picture made for television',
        'best actor in a television miniseries or motion picture',
        'best actor television miniseries',
        'best performance by an actor in a mini-series or motion picture made for tv',
        'best actor in a mini-series or motion picture made for tv',
        'best actor in a tv miniseries or motion picture',
        'best actor tv miniseries',
    ],
    'best performance by an actress in a supporting role in a series, mini-series or motion picture made for television': [
        'best performance by an actress in a supporting role in a series, mini-series or motion picture made for television',
        'best actress in a supporting role in a series, mini-series or motion picture made for television',
        'best supporting actress in a series, mini-series or motion picture made for television',
        'best supporting actress in a television series, mini-series or motion picture',
        'best supporting actress in television',
        'best supporting actress television series, mini-series, motion picture',
        'best television supporting actress',
        'best performance by an actress in a supporting role in a series, mini-series or motion picture made for tv',
        'best actress in a supporting role in a series, mini-series or motion picture made for tv',
        'best supporting actress in a series, mini-series or motion picture made for tv',
        'best supporting actress in a tv series, mini-series or motion picture',
        'best supporting actress in tv',
        'best supporting actress tv series, mini-series, motion picture',
        'best tv supporting actress',    
    ],
    'best performance by an actor in a supporting role in a series, mini-series or motion picture made for television': [
        'best performance by an actor in a supporting role in a series, mini-series or motion picture made for television',
        'best actor in a supporting role in a series, mini-series or motion picture made for television',
        'best supporting actor in a series, mini-series or motion picture made for television',
        'best supporting actor in a television series, mini-series or motion picture',
        'best supporting actor in television',
        'best supporting actor television series, mini-series, motion picture',
        'best television supporting actor',
        'best performance by an actor in a supporting role in a series, mini-series or motion picture made for tv',
        'best actor in a supporting role in a series, mini-series or motion picture made for tv',
        'best supporting actor in a series, mini-series or motion picture made for tv',
        'best supporting actor in a tv series, mini-series or motion picture',
        'best supporting actor in tv',
        'best supporting actor tv series, mini-series, motion picture',
        'best tv supporting actor',    
    ]
}